### ISSUE TITLE
Unity Version

### ISSUE THREAD

**Issue by fsmilu** [Kokyung/UnityChatGPTScriptGenerator#1]
유니티 2022버전 이상 인까요? 혹시

**Comment by fsmilu** [comment]
설치하고 키 입력했는데 계속 "API Key is Empty" 라고해요..어떻하죠??
![image](https://user-images.githubusercontent.com/32787951/231084537-13df8e4c-9f7a-41ab-b1b3-a346dc6e3127.png)

**Comment by Kokyung** [comment]
본 에셋은 2020.3.35f1에서 제작하였습니다.
-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2023-04-11 (화) 14:54:35 (GMT+09:00)
Subject: [Kokyung/UnityChatGPTScriptGenerator] Unity Version (Issue #1)

유니티 2022버전 이상 인까요? 혹시

**Comment by Kokyung** [comment]
API Key 체크가 안되는 이슈 확인했습니다. 곧 수정하겠습니다.

**Comment by Kokyung** [comment]
> 설치하고 키 입력했는데 계속 "API Key is Empty" 라고해요..어떻하죠?? ![image](https://user-images.githubusercontent.com/32787951/231084537-13df8e4c-9f7a-41ab-b1b3-a346dc6e3127.png)

수정되었습니다. 패키지 삭제후 재설치 바랍니다.
